#ifndef IKEA_PS2014_WIFI_CONFIG_H
#define IKEA_PS2014_WIFI_CONFIG_H

#define GRANULARITY 5
#define END_POS 48000
#define OPEN (-1)
#define CLOSE 1

#define HOMED_NO 0
#define HOMED_COARSE 1
#define HOMED_FINE 2

#endif //IKEA_PS2014_WIFI_CONFIG_H
